# Generated by Django 4.1.1 on 2022-09-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField()),
                ('date_submitted', models.DateTimeField()),
                ('document_link', models.CharField(max_length=300)),
                ('departement_head_approval', models.BooleanField()),
                ('ceo_approval', models.BooleanField()),
            ],
        ),
    ]
