# Generated by Django 4.1.1 on 2022-09-21 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_DAO', models.CharField(default='N:0000', max_length=25)),
                ('description_DAO', models.CharField(default='DAO', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_submitted', models.DateTimeField(default=None)),
                ('document_link', models.CharField(max_length=300)),
                ('departement_head_approval', models.BooleanField()),
                ('ceo_approval', models.BooleanField()),
            ],
        ),
    ]
