# Generated by Django 4.1.1 on 2022-09-18 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0002_dao_created_at_dao_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dao',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 11, 56, 34, 64727, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dao',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 11, 56, 34, 64751, tzinfo=datetime.timezone.utc)),
        ),
    ]
