# Generated by Django 4.1.1 on 2022-09-18 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0005_alter_dao_created_at_alter_dao_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dao',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='dao',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 11, 57, 20, 523663, tzinfo=datetime.timezone.utc)),
        ),
    ]
