# Generated by Django 4.1.1 on 2022-09-18 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0009_alter_dao_created_at_alter_dao_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dao',
            name='description_DAO',
            field=models.CharField(default='DAO', max_length=200),
        ),
        migrations.AddField(
            model_name='dao',
            name='id_DAO',
            field=models.CharField(default='N:0000', max_length=25),
        ),
        migrations.AlterField(
            model_name='dao',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 12, 31, 41, 42079, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dao',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 12, 31, 41, 42098, tzinfo=datetime.timezone.utc)),
        ),
    ]
