# Generated by Django 4.1.1 on 2022-09-19 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DAO', '0011_remove_dao_created_at_remove_dao_date_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dao',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dao',
            name='date_submitted',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='dao',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dao',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
